require('meggalord.lsp')
require('meggalord.tele')
require('meggalord.nvimtreesit')
require('meggalord.vimgitsigns')
require('meggalord.tglterm')
require('meggalord.nvimtree')
require('meggalord.webdevicons')
